version: 2

before:
  hooks:
    - go mod tidy
    - pnpm install
    - pnpm build

builds:
  - id: mitmflow
    main: .
    binary: mitmflow
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: mitmflow
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

dockers:
  - image_templates:
      - "ghcr.io/sudorandom/mitmflow:{{ .Version }}-amd64"
      - "ghcr.io/sudorandom/mitmflow:latest-amd64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=A modern web UI for mitmproxy"
      - "--label=org.opencontainers.image.url=https://github.com/sudorandom/mitmflow"
      - "--label=org.opencontainers.image.source=https://github.com/sudorandom/mitmflow"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"
    
  - image_templates:
      - "ghcr.io/sudorandom/mitmflow:{{ .Version }}-arm64"
      - "ghcr.io/sudorandom/mitmflow:latest-arm64"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=A modern web UI for mitmproxy"
      - "--label=org.opencontainers.image.url=https://github.com/sudorandom/mitmflow"
      - "--label=org.opencontainers.image.source=https://github.com/sudorandom/mitmflow"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"

docker_manifests:
  - name_template: "ghcr.io/sudorandom/mitmflow:{{ .Version }}"
    image_templates:
      - "ghcr.io/sudorandom/mitmflow:{{ .Version }}-amd64"
      - "ghcr.io/sudorandom/mitmflow:{{ .Version }}-arm64"
  
  - name_template: "ghcr.io/sudorandom/mitmflow:latest"
    image_templates:
      - "ghcr.io/sudorandom/mitmflow:latest-amd64"
      - "ghcr.io/sudorandom/mitmflow:latest-arm64"
