# Generated by the connect-python plugin.
#
# The following code is derived from the protoc-gen-connect-python project:
# https://github.com/connectrpc/connect-python
#
# Copyright 2022-2023 The Connect Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from connectrpc.client import Client
from connectrpc.server import Service
from connectrpc.transports import Transport
from mitmflow.v1 import mitmflow_pb2
from google.protobuf import empty_pb2

class MITMFlow(Service):
    """
    The service definition.
    """
    service_name = "mitmflow.v1.MITMFlow"

    def export_flow(self, request_stream):
        """
        Sends a stream of flows. The client will stream flows,
        and the server will return a single reply when the stream ends.
        """
        return self.unary_stream(
            "/mitmflow.v1.MITMFlow/ExportFlow",
            request_stream,
            mitmflow_pb2.ExportReply,
        )

    def stream_flows(self, request):
        """
        Sends a stream of flows. The server will stream flows,
        and the client will receive them.
        """
        return self.stream_unary(
            "/mitmflow.v1.MITMFlow/StreamFlows",
            request,
            mitmflow_pb2.Flow,
        )

class MITMFlowClient(Client):
    """
    The service definition.
    """
    service_name = "mitmflow.v1.MITMFlow"

    def export_flow(self, request_stream, **kwargs):
        """
        Sends a stream of flows. The client will stream flows,
        and the server will return a single reply when the stream ends.
        """
        return self.unary_stream(
            "/mitmflow.v1.MITMFlow/ExportFlow",
            request_stream,
            mitmflow_pb2.ExportReply,
            **kwargs
        )

    def stream_flows(self, request, **kwargs):
        """
        Sends a stream of flows. The server will stream flows,
        and the client will receive them.
        """
        return self.stream_unary(
            "/mitmflow.v1.MITMFlow/StreamFlows",
            request,
            mitmflow_pb2.Flow,
            **kwargs
        )