# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mitmflow.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10mitmflow.proto\x12\x0bmitmflow.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto"\xc9\x01\n\x04Flow\x12\n\n\x02id\x18\x01 \x01(\t\x12&\n\x07request\x18\x02 \x01(\x0b2\x15.mitmflow.v1.Request\x12(\n\x08response\x18\x03 \x01(\x0b2\x16.mitmflow.v1.Response\x123\n\x0ftimestamp_start\x18\x04 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12\x13\n\x0bduration_ms\x18\x05 \x01(\x01\x12\x11\n\tclient_ip\x18\x06 \x01(\t"\xa1\x01\n\x07Request\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x122\n\x07headers\x18\x03 \x03(\x0b2!.mitmflow.v1.Request.HeadersEntry\x12\x0f\n\x07content\x18\x04 \x01(\x0c\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x028\x01"\x9b\x01\n\x08Response\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x123\n\x07headers\x18\x02 \x03(\x0b2".mitmflow.v1.Response.HeadersEntry\x12\x0f\n\x07content\x18\x03 \x01(\x0c\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x028\x01"J\n\x0bExportReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x10\n\x08received\x18\x02 \x01(\x08\x12\x18\n\x10flows_processed\x18\x03 \x01(\x042\x85\x01\n\x08MITMFlow\x129\n\nExportFlow\x12\x11.mitmflow.v1.Flow\x1a\x18.mitmflow.v1.ExportReply"\x00(\x01\x12>\n\x0bStreamFlows\x12\x16.google.protobuf.Empty\x1a\x11.mitmflow.v1.Flow"\x000\x01B\x1e\n\x1acom.github.sudorandom.mitmflowP\x01b\x06proto3')


_FLOW = DESCRIPTOR.message_types_by_name['Flow']
_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_REQUEST_HEADERSENTRY = _REQUEST.nested_types_by_name['HeadersEntry']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
_RESPONSE_HEADERSENTRY = _RESPONSE.nested_types_by_name['HeadersEntry']
_EXPORTREPLY = DESCRIPTOR.message_types_by_name['ExportReply']
Flow = _reflection.GeneratedProtocolMessageType('Flow', (_message.Message,), {
  'DESCRIPTOR' : _FLOW,
  '__module__' : 'mitmflow_pb2'
  # @@protoc_insertion_point(class_scope:mitmflow.v1.Flow)
  })
_sym_db.RegisterMessage(Flow)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'HeadersEntry' : _reflection.GeneratedProtocolMessageType('HeadersEntry', (_message.Message,), {
    'DESCRIPTOR' : _REQUEST_HEADERSENTRY,
    '__module__' : 'mitmflow_pb2'
    # @@protoc_insertion_point(class_scope:mitmflow.v1.Request.HeadersEntry)
    })
  ,
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'mitmflow_pb2'
  # @@protoc_insertion_point(class_scope:mitmflow.v1.Request)
  })
_sym_db.RegisterMessage(Request)
_sym_db.RegisterMessage(Request.HeadersEntry)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'HeadersEntry' : _reflection.GeneratedProtocolMessageType('HeadersEntry', (_message.Message,), {
    'DESCRIPTOR' : _RESPONSE_HEADERSENTRY,
    '__module__' : 'mitmflow_pb2'
    # @@protoc_insertion_point(class_scope:mitmflow.v1.Response.HeadersEntry)
    })
  ,
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'mitmflow_pb2'
  # @@protoc_insertion_point(class_scope:mitmflow.v1.Response)
  })
_sym_db.RegisterMessage(Response)
_sym_db.RegisterMessage(Response.HeadersEntry)

ExportReply = _reflection.GeneratedProtocolMessageType('ExportReply', (_message.Message,), {
  'DESCRIPTOR' : _EXPORTREPLY,
  '__module__' : 'mitmflow_pb2'
  # @@protoc_insertion_point(class_scope:mitmflow.v1.ExportReply)
  })
_sym_db.RegisterMessage(ExportReply)

_MITMFLOW = DESCRIPTOR.services_by_name['MITMFlow']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032com.github.sudorandom.mitmflowP\001'
  _REQUEST_HEADERSENTRY._options = None
  _REQUEST_HEADERSENTRY._serialized_options = b'8\001'
  _RESPONSE_HEADERSENTRY._options = None
  _RESPONSE_HEADERSENTRY._serialized_options = b'8\001'
  _FLOW._serialized_start=98
  _FLOW._serialized_end=299
  _REQUEST._serialized_start=302
  _REQUEST._serialized_end=463
  _REQUEST_HEADERSENTRY._serialized_start=417
  _REQUEST_HEADERSENTRY._serialized_end=463
  _RESPONSE._serialized_start=466
  _RESPONSE._serialized_end=621
  _RESPONSE_HEADERSENTRY._serialized_start=417
  _RESPONSE_HEADERSENTRY._serialized_end=463
  _EXPORTREPLY._serialized_start=623
  _EXPORTREPLY._serialized_end=697
  _MITMFLOW._serialized_start=700
  _MITMFLOW._serialized_end=833
# @@protoc_insertion_point(module_scope)