# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: mitmflow/v1/mitmflow.proto

from collections.abc import AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import mitmflow.v1.mitmflow_pb2 as mitmflow_dot_v1_dot_mitmflow__pb2


class Service(Protocol):
    async def export_flow(self, request: AsyncIterator[mitmflow_dot_v1_dot_mitmflow__pb2.ExportFlowRequest], ctx: RequestContext) -> mitmflow_dot_v1_dot_mitmflow__pb2.ExportFlowResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def stream_flows(self, request: mitmflow_dot_v1_dot_mitmflow__pb2.StreamFlowsRequest, ctx: RequestContext) -> AsyncIterator[mitmflow_dot_v1_dot_mitmflow__pb2.StreamFlowsResponse]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ServiceASGIApplication(ConnectASGIApplication):
    def __init__(self, service: Service, *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/mitmflow.v1.Service/ExportFlow": Endpoint.client_stream(
                    method=MethodInfo(
                        name="ExportFlow",
                        service_name="mitmflow.v1.Service",
                        input=mitmflow_dot_v1_dot_mitmflow__pb2.ExportFlowRequest,
                        output=mitmflow_dot_v1_dot_mitmflow__pb2.ExportFlowResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.export_flow,
                ),
                "/mitmflow.v1.Service/StreamFlows": Endpoint.server_stream(
                    method=MethodInfo(
                        name="StreamFlows",
                        service_name="mitmflow.v1.Service",
                        input=mitmflow_dot_v1_dot_mitmflow__pb2.StreamFlowsRequest,
                        output=mitmflow_dot_v1_dot_mitmflow__pb2.StreamFlowsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.stream_flows,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/mitmflow.v1.Service"


class ServiceClient(ConnectClient):
    async def export_flow(
        self,
        request: AsyncIterator[mitmflow_dot_v1_dot_mitmflow__pb2.ExportFlowRequest],
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> mitmflow_dot_v1_dot_mitmflow__pb2.ExportFlowResponse:
        return await self.execute_client_stream(
            request=request,
            method=MethodInfo(
                name="ExportFlow",
                service_name="mitmflow.v1.Service",
                input=mitmflow_dot_v1_dot_mitmflow__pb2.ExportFlowRequest,
                output=mitmflow_dot_v1_dot_mitmflow__pb2.ExportFlowResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def stream_flows(
        self,
        request: mitmflow_dot_v1_dot_mitmflow__pb2.StreamFlowsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> AsyncIterator[mitmflow_dot_v1_dot_mitmflow__pb2.StreamFlowsResponse]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="StreamFlows",
                service_name="mitmflow.v1.Service",
                input=mitmflow_dot_v1_dot_mitmflow__pb2.StreamFlowsRequest,
                output=mitmflow_dot_v1_dot_mitmflow__pb2.StreamFlowsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class ServiceSync(Protocol):
    def export_flow(self, request: Iterator[mitmflow_dot_v1_dot_mitmflow__pb2.ExportFlowRequest], ctx: RequestContext) -> mitmflow_dot_v1_dot_mitmflow__pb2.ExportFlowResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def stream_flows(self, request: mitmflow_dot_v1_dot_mitmflow__pb2.StreamFlowsRequest, ctx: RequestContext) -> Iterator[mitmflow_dot_v1_dot_mitmflow__pb2.StreamFlowsResponse]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: ServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/mitmflow.v1.Service/ExportFlow": EndpointSync.client_stream(
                    method=MethodInfo(
                        name="ExportFlow",
                        service_name="mitmflow.v1.Service",
                        input=mitmflow_dot_v1_dot_mitmflow__pb2.ExportFlowRequest,
                        output=mitmflow_dot_v1_dot_mitmflow__pb2.ExportFlowResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.export_flow,
                ),
                "/mitmflow.v1.Service/StreamFlows": EndpointSync.server_stream(
                    method=MethodInfo(
                        name="StreamFlows",
                        service_name="mitmflow.v1.Service",
                        input=mitmflow_dot_v1_dot_mitmflow__pb2.StreamFlowsRequest,
                        output=mitmflow_dot_v1_dot_mitmflow__pb2.StreamFlowsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.stream_flows,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/mitmflow.v1.Service"


class ServiceClientSync(ConnectClientSync):
    def export_flow(
        self,
        request: Iterator[mitmflow_dot_v1_dot_mitmflow__pb2.ExportFlowRequest],
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> mitmflow_dot_v1_dot_mitmflow__pb2.ExportFlowResponse:
        return self.execute_client_stream(
            request=request,
            method=MethodInfo(
                name="ExportFlow",
                service_name="mitmflow.v1.Service",
                input=mitmflow_dot_v1_dot_mitmflow__pb2.ExportFlowRequest,
                output=mitmflow_dot_v1_dot_mitmflow__pb2.ExportFlowResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def stream_flows(
        self,
        request: mitmflow_dot_v1_dot_mitmflow__pb2.StreamFlowsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> Iterator[mitmflow_dot_v1_dot_mitmflow__pb2.StreamFlowsResponse]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="StreamFlows",
                service_name="mitmflow.v1.Service",
                input=mitmflow_dot_v1_dot_mitmflow__pb2.StreamFlowsRequest,
                output=mitmflow_dot_v1_dot_mitmflow__pb2.StreamFlowsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
